/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_HEART_RATE_PB_H_INCLUDED
#define PB_HEART_RATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Notify {
    uint32_t index; /* packet sequence number */
    pb_byte_t hr_buffer[10]; /* data payload */
} Notify;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Notify_init_default                      {0, {0}}
#define Notify_init_zero                         {0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define Notify_index_tag                         1
#define Notify_hr_buffer_tag                     2

/* Struct field encoding specification for nanopb */
#define Notify_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, hr_buffer,         2)
#define Notify_CALLBACK NULL
#define Notify_DEFAULT NULL

extern const pb_msgdesc_t Notify_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Notify_fields &Notify_msg

/* Maximum encoded size of messages (where known) */
#define HEART_RATE_PB_H_MAX_SIZE                 Notify_size
#define Notify_size                              18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
